/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DeedsRouteImport } from './routes/deeds'
import { Route as FadlRouteImport } from './routes/fadl'
import { Route as FarmRouteImport } from './routes/farm'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as MaqamatRouteImport } from './routes/maqamat'
import { Route as MercyRouteImport } from './routes/mercy'
import { Route as PrayerRouteImport } from './routes/prayer'
import { Route as ReportRouteImport } from './routes/report'
import { Route as SabrRouteImport } from './routes/sabr'
import { Route as SalawatRouteImport } from './routes/salawat'
import { Route as SectionsRouteImport } from './routes/sections'
import { Route as TadabburRouteImport } from './routes/tadabbur'
import { Route as TawbahRouteImport } from './routes/tawbah'
import { Route as WasfRouteImport } from './routes/wasf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DeedsRoute = DeedsRouteImport.update({
  id: '/deeds',
  path: '/deeds',
  getParentRoute: () => rootRouteImport,
} as any)
const FadlRoute = FadlRouteImport.update({
  id: '/fadl',
  path: '/fadl',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmRoute = FarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const MaqamatRoute = MaqamatRouteImport.update({
  id: '/maqamat',
  path: '/maqamat',
  getParentRoute: () => rootRouteImport,
} as any)
const MercyRoute = MercyRouteImport.update({
  id: '/mercy',
  path: '/mercy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerRoute = PrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const SabrRoute = SabrRouteImport.update({
  id: '/sabr',
  path: '/sabr',
  getParentRoute: () => rootRouteImport,
} as any)
const SalawatRoute = SalawatRouteImport.update({
  id: '/salawat',
  path: '/salawat',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionsRoute = SectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => rootRouteImport,
} as any)
const TadabburRoute = TadabburRouteImport.update({
  id: '/tadabbur',
  path: '/tadabbur',
  getParentRoute: () => rootRouteImport,
} as any)
const TawbahRoute = TawbahRouteImport.update({
  id: '/tawbah',
  path: '/tawbah',
  getParentRoute: () => rootRouteImport,
} as any)
const WasfRoute = WasfRouteImport.update({
  id: '/wasf',
  path: '/wasf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/deeds': typeof DeedsRoute
  '/fadl': typeof FadlRoute
  '/farm': typeof FarmRoute
  '/feedback': typeof FeedbackRoute
  '/maqamat': typeof MaqamatRoute
  '/mercy': typeof MercyRoute
  '/prayer': typeof PrayerRoute
  '/report': typeof ReportRoute
  '/sabr': typeof SabrRoute
  '/salawat': typeof SalawatRoute
  '/sections': typeof SectionsRoute
  '/tadabbur': typeof TadabburRoute
  '/tawbah': typeof TawbahRoute
  '/wasf': typeof WasfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/deeds': typeof DeedsRoute
  '/fadl': typeof FadlRoute
  '/farm': typeof FarmRoute
  '/feedback': typeof FeedbackRoute
  '/maqamat': typeof MaqamatRoute
  '/mercy': typeof MercyRoute
  '/prayer': typeof PrayerRoute
  '/report': typeof ReportRoute
  '/sabr': typeof SabrRoute
  '/salawat': typeof SalawatRoute
  '/sections': typeof SectionsRoute
  '/tadabbur': typeof TadabburRoute
  '/tawbah': typeof TawbahRoute
  '/wasf': typeof WasfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/deeds': typeof DeedsRoute
  '/fadl': typeof FadlRoute
  '/farm': typeof FarmRoute
  '/feedback': typeof FeedbackRoute
  '/maqamat': typeof MaqamatRoute
  '/mercy': typeof MercyRoute
  '/prayer': typeof PrayerRoute
  '/report': typeof ReportRoute
  '/sabr': typeof SabrRoute
  '/salawat': typeof SalawatRoute
  '/sections': typeof SectionsRoute
  '/tadabbur': typeof TadabburRoute
  '/tawbah': typeof TawbahRoute
  '/wasf': typeof WasfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/deeds'
    | '/fadl'
    | '/farm'
    | '/feedback'
    | '/maqamat'
    | '/mercy'
    | '/prayer'
    | '/report'
    | '/sabr'
    | '/salawat'
    | '/sections'
    | '/tadabbur'
    | '/tawbah'
    | '/wasf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/deeds'
    | '/fadl'
    | '/farm'
    | '/feedback'
    | '/maqamat'
    | '/mercy'
    | '/prayer'
    | '/report'
    | '/sabr'
    | '/salawat'
    | '/sections'
    | '/tadabbur'
    | '/tawbah'
    | '/wasf'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calendar'
    | '/deeds'
    | '/fadl'
    | '/farm'
    | '/feedback'
    | '/maqamat'
    | '/mercy'
    | '/prayer'
    | '/report'
    | '/sabr'
    | '/salawat'
    | '/sections'
    | '/tadabbur'
    | '/tawbah'
    | '/wasf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  DeedsRoute: typeof DeedsRoute
  FadlRoute: typeof FadlRoute
  FarmRoute: typeof FarmRoute
  FeedbackRoute: typeof FeedbackRoute
  MaqamatRoute: typeof MaqamatRoute
  MercyRoute: typeof MercyRoute
  PrayerRoute: typeof PrayerRoute
  ReportRoute: typeof ReportRoute
  SabrRoute: typeof SabrRoute
  SalawatRoute: typeof SalawatRoute
  SectionsRoute: typeof SectionsRoute
  TadabburRoute: typeof TadabburRoute
  TawbahRoute: typeof TawbahRoute
  WasfRoute: typeof WasfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deeds': {
      id: '/deeds'
      path: '/deeds'
      fullPath: '/deeds'
      preLoaderRoute: typeof DeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fadl': {
      id: '/fadl'
      path: '/fadl'
      fullPath: '/fadl'
      preLoaderRoute: typeof FadlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm': {
      id: '/farm'
      path: '/farm'
      fullPath: '/farm'
      preLoaderRoute: typeof FarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maqamat': {
      id: '/maqamat'
      path: '/maqamat'
      fullPath: '/maqamat'
      preLoaderRoute: typeof MaqamatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercy': {
      id: '/mercy'
      path: '/mercy'
      fullPath: '/mercy'
      preLoaderRoute: typeof MercyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer': {
      id: '/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof PrayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sabr': {
      id: '/sabr'
      path: '/sabr'
      fullPath: '/sabr'
      preLoaderRoute: typeof SabrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salawat': {
      id: '/salawat'
      path: '/salawat'
      fullPath: '/salawat'
      preLoaderRoute: typeof SalawatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sections': {
      id: '/sections'
      path: '/sections'
      fullPath: '/sections'
      preLoaderRoute: typeof SectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tadabbur': {
      id: '/tadabbur'
      path: '/tadabbur'
      fullPath: '/tadabbur'
      preLoaderRoute: typeof TadabburRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tawbah': {
      id: '/tawbah'
      path: '/tawbah'
      fullPath: '/tawbah'
      preLoaderRoute: typeof TawbahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wasf': {
      id: '/wasf'
      path: '/wasf'
      fullPath: '/wasf'
      preLoaderRoute: typeof WasfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  DeedsRoute: DeedsRoute,
  FadlRoute: FadlRoute,
  FarmRoute: FarmRoute,
  FeedbackRoute: FeedbackRoute,
  MaqamatRoute: MaqamatRoute,
  MercyRoute: MercyRoute,
  PrayerRoute: PrayerRoute,
  ReportRoute: ReportRoute,
  SabrRoute: SabrRoute,
  SalawatRoute: SalawatRoute,
  SectionsRoute: SectionsRoute,
  TadabburRoute: TadabburRoute,
  TawbahRoute: TawbahRoute,
  WasfRoute: WasfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
